### ISSUE TITLE
THE BOT NOT WORKING

### ISSUE THREAD

**Issue by iahmaadi** [ryanpag3/discord-score-bot#101]
Hello , the bot has been disconnecting for couple days and now it not working anymore, it been more than hour .
THANKS

**Comment by ryanpag3** [comment]
Hi there, 

Yep, been doing some changes on the networking side of things which caused some unintentional downtime. Should be cleared up now.

If you need high availability for the bot, the instance that I host **should not be treated as such.** I build docker containers of the bot for each build that you can deploy and manage yourself. You can see the instructions in the README file.
