### ISSUE TITLE
The explanation for types of scores should not be under the `add` command

### ISSUE THREAD

**Issue by hb20007** [ryanpag3/discord-score-bot#124]
I found the documentation on scoreboards difficult to understand.

Currently, the documentation starts like this:

![Documentation screenshot](https://user-images.githubusercontent.com/8860322/152412376-740a0700-c841-4ee4-bc24-f0052c35d239.png)

I do not think the documentation for the types of scores should be under the `add` command. It would be better if it comes before since it's not necessarily related to it. Also, the fact that this information comes under the `add` command made me assume that this command will also create the scoreboard, because it says "Scoreboard: create a scoreboard and assign a score to it".

**Comment by ryanpag3** [comment]
Thanks for reporting. This has been addressed in the new bot that I've been working on that will replace the score bot. I will be closing this issue for now.
