### ISSUE TITLE
channel keywords being picked up serverwide

### ISSUE THREAD

**Issue by shleechan** [ryanpag3/discord-score-bot#71]
Recently migrated from Tally-bot in one of my Discord servers where we have a bunch of people trying to keep track of what they're creating each month. Made channel scores, and what I thought were channel-specific keywords for each of the channel scores, but the keywords are being picked up in -every- channel on the server and added to the tallies which is making keeping accurate numbers difficult (even though the keywords are, for the most part, not things we'd use in day-to-day conversation). is this working as intended or do I need to do something on my end to fix this?

**Comment by ryanpag3** [comment]
Hey there @shleechan, that is my fault. I honestly hadn't thought of that scenario. I'll get that fixed :)
