### ISSUE TITLE
Can't add to my server 

### ISSUE THREAD

**Issue by riannevdw** [ryanpag3/discord-score-bot#95]
I have tried the bot in my test server without a problem but can't add it to my actual server for some reason unfortunately

The server that I want it added to is https://discord.gg/bEHQBbq

**Comment by ryanpag3** [comment]
Hi @riannevdw, what is it saying when you try to include it?

**Comment by riannevdw** [comment]
Hi Ryan,

It acts like it has added but when I go to the server it's not in there if
that makes sense

It goes through the whole adding process but doesn't actually add it

kind regards,

Rianne van der Woude

**Comment by ryanpag3** [comment]
My best guess is it is permission related. I would double check that the roles assigned to the bot have the requested read/write permissions. If you want to double check the permissions requested, the invite page for the bot lists them out. Hope this helps :)

**Comment by riannevdw** [comment]
Hi Ryan,

I have tried to edit permissions and it shows in my server log that the bot
was added but I can't see it anywhere else which means I can't assign a
role to it or use it unfortunately as it doesn't react to the commands

kind regards,

Rianne van der Woude

**Comment by ryanpag3** [comment]
Hmmm that's really strange. I've never seen that before. I'll look into it and see if I can reproduce it and respond here if I figure it out.
